name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

      # - name: Setup Node
      #   - uses: actions/setup-node@v3
      #     with:
      #       node-version: 18.14.2

      # - name: Install dependencies
      #   run: yarn

      # - name: Generate
      #   run: yarn generate

      # - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist