name: Build and Deploy...
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: |
          npm install yarn --force
          yarn install

      # - name: Test application
      #   run: |
      #     yarn test

      - name: Build application
        run: |
          yarn build
          yarn generate
      - name: Deploy on server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          source: "/home/runner/work/vue-pwa-carvann/vue-pwa-carvann/.output/public"
          target: ${{ secrets.DEV_PATH }}